# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvideo.proto\x12\rvideo_service\".\n\x0cVideoRequest\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\"7\n\x16ProcessedVideoResponse\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t2h\n\x0cVideoService\x12X\n\x0cProcessVideo\x12\x1b.video_service.VideoRequest\x1a%.video_service.ProcessedVideoResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEOREQUEST']._serialized_start=30
  _globals['_VIDEOREQUEST']._serialized_end=76
  _globals['_PROCESSEDVIDEORESPONSE']._serialized_start=78
  _globals['_PROCESSEDVIDEORESPONSE']._serialized_end=133
  _globals['_VIDEOSERVICE']._serialized_start=135
  _globals['_VIDEOSERVICE']._serialized_end=239
# @@protoc_insertion_point(module_scope)
